"""Create customers table

Revision ID: 46273716ec00
Revises: fe3f4c340a1f
Create Date: 2026-08-13 05:55:13.594870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46273716ec00'
down_revision: Union[str, Sequence[str], None] = 'fe3f4c340a1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('businesses_owner_email_key'), 'businesses', type_='unique')
    op.create_index(op.f('ix_businesses_id'), 'businesses', ['id'], unique=False)
    op.create_index(op.f('ix_businesses_owner_email'), 'businesses', ['owner_email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_businesses_owner_email'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_id'), table_name='businesses')
    op.create_unique_constraint(op.f('businesses_owner_email_key'), 'businesses', ['owner_email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
