"""Add barcode to products

Revision ID: 85cfb909b7e5
Revises: 5b1eac21f77b
Create Date: 2026-08-15 16:37:52.138399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85cfb909b7e5'
down_revision: Union[str, Sequence[str], None] = '5b1eac21f77b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('barcode', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'barcode')
    # ### end Alembic commands ###
