"""Add receipt_no to orders

Revision ID: a357e977488f
Revises: c7d2cf1dd292
Create Date: 2026-08-14 15:53:40.715758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a357e977488f'
down_revision: Union[str, Sequence[str], None] = 'c7d2cf1dd292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('receipt_no', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'receipt_no')
    # ### end Alembic commands ###
